const std = @import("std");

pub const Server = @import("Server/root.zig");

// TODO: I feel like this (and Status) can be done better and/or cleaner
// https://www.iana.org/assignments/http-methods/http-methods.xhtml
pub const Method = enum {
    const map = std.StaticStringMap(Method).initComptime(.{
        .{ "GET", .get },
        .{ "HEAD", .head },
        .{ "POST", .post },
        .{ "PUT", .put },
        .{ "DELETE", .delete },
        .{ "CONNECT", .connect },
        .{ "OPTIONS", .options },
        .{ "TRACE", .trace },
        .{ "PATCH", .patch },
        .{ "QUERY", .query },
        .{ "LINK", .link },
        .{ "UNLINK", .unlink },

        .{ "COPY", .copy },
        .{ "LOCK", .lock },
        .{ "UNLOCK", .unlock },
        .{ "MOVE", .move },
        .{ "MKCOL", .mkcol },
        .{ "PROPFIND", .propfind },
        .{ "PROPPATCH", .proppatch },
        .{ "MKACTIVITY", .mkactivity },
        .{ "MKWORKSPACE", .mkworkspace },
        .{ "MKCALENDAR", .mkcalendar },
        .{ "CHECKIN", .checkin },
        .{ "CHECKOUT", .checkout },
        .{ "UNCHECKOUT", .uncheckout },
        .{ "VERSION-CONTROL", .version_ctrl },
        .{ "BASELINE-CONTROL", .baseline_ctrl },
        .{ "LABEL", .label },
        .{ "MERGE", .merge },
        .{ "REPORT", .report },
        .{ "ACL", .acl },
        .{ "UPDATE", .update },
        .{ "MKREDIRECTREF", .mkredirectref },
        .{ "UPDATEREDIRECTREF", .updateredirectref },
        .{ "ORDERPATCH", .order_patch },
        .{ "BIND", .bind },
        .{ "UNBIND", .unbind },
        .{ "REBIND", .rebind },
        .{ "SEARCH", .search },
    });

    get,
    head,
    post,
    put,
    delete,
    connect,
    options,
    trace,
    patch,
    query,
    link,
    unlink,

    copy,
    lock,
    unlock,
    move,
    mkcol,
    propfind,
    proppatch,
    mkactivity,
    mkworkspace,
    mkcalendar,
    checkin,
    checkout,
    uncheckout,
    version_ctrl,
    baseline_ctrl,
    label,
    merge,
    report,
    acl,
    update,
    mkredirectref,
    updateredirectref,
    order_patch,
    bind,
    unbind,
    rebind,
    search,

    pub fn from(str: []const u8) ?Method {
        return map.get(str);
    }
};

// https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
pub const Status = enum(u9) {
    @"continue" = 100,
    switching_protocols = 101,
    processing = 102,
    early_hints = 103,
    // temporary, expires 11/13/2026ß
    upload_resumption = 104,

    ok = 200,
    created = 201,
    accepted = 202,
    non_authoritative = 203,
    no_content = 204,
    reset_content = 205,
    partial_content = 206,
    multi_status = 207,
    already_reported = 208,
    im_used = 226,

    multiple_choices = 300,
    moved_permanently = 301,
    found = 302,
    see_other = 303,
    not_modified = 304,
    use_proxy = 305, // deprecated
    temp_redirect = 307,
    perm_redirect = 308,

    bad_request = 400,
    unauthorized = 401,
    payment_required = 402,
    forbidden = 403,
    not_found = 404,
    method_not_allowed = 405,
    not_acceptable = 406,
    proxy_auth_required = 407,
    request_timeout = 408,
    conflict = 409,
    gone = 410,
    length_required = 411,
    precondition_failed = 412,
    content_too_large = 413,
    uri_too_long = 414,
    unsupported_media = 415,
    bad_range = 416,
    expect_failed = 417,
    misdirected = 421,
    unprocessable = 422,
    locked = 423,
    failed_dependency = 424,
    too_early = 425,
    upgrade_required = 426,
    precondition_required = 428,
    too_many_requests = 429,
    headers_too_large = 431,
    legal_reasons = 451,

    server_error = 500,
    not_implemented = 501,
    bad_gateway = 502,
    unavailable = 503,
    gateway_timeout = 504,
    version_not_supported = 505,
    variant_negotiates = 506,
    insufficient_storage = 507,
    loop_detected = 508,
    not_extended = 510, // obsoleted
    network_auth_required = 511,

    pub fn string(self: Status) []const u8 {
        return switch (self) {
            .@"continue" => "Continue",
            .switching_protocols => "Switching Protocols",
            .processing => "Processing",
            .early_hints => "Early Hints",
            .upload_resumption => "Upload Resumption Supported",

            .ok => "OK",
            .created => "Created",
            .accepted => "Accepted",
            .non_authoritative => "Non-Authoritative Information",
            .no_content => "No Content",
            .reset_content => "Reset Content",
            .partial_content => "Partial Content",
            .multi_status => "Multi-Status",
            .already_reported => "Already Reported",
            .im_used => "IM Used",

            .multiple_choices => "Multiple Choices",
            .moved_permanently => "Moved Permanently",
            .found => "Found",
            .see_other => "See Other",
            .not_modified => "Not Modified",
            .use_proxy => "Use Proxy",
            .temp_redirect => "Temporary Redirect",
            .perm_redirect => "Permanent Redirect",

            .bad_request => "Bad Request",
            .unauthorized => "Unauthorized",
            .payment_required => "Payment Required",
            .forbidden => "Forbidden",
            .not_found => "Not Found",
            .method_not_allowed => "Method Not Allowed",
            .not_acceptable => "Not Acceptable",
            .proxy_auth_required => "Proxy Authentication Required",
            .request_timeout => "Request Timeout",
            .conflict => "Conflict",
            .gone => "Gone",
            .length_required => "Length Required",
            .precondition_failed => "Precondition Failed",
            .content_too_large => "Content Too Large",
            .uri_too_long => "URI Too Long",
            .unsupported_media => "Unsupported Media Type",
            .bad_range => "Range Not Satisfiable",
            .expect_failed => "Expectation Failed",
            .misdirected => "Misdirected Request",
            .unprocessable => "Unprocessable Content",
            .locked => "Locked",
            .failed_dependency => "Failed Dependency",
            .too_early => "Too Early",
            .upgrade_required => "Upgrade Required",
            .precondition_required => "Precondition Required",
            .too_many_requests => "Too Many Requests",
            .headers_too_large => "Request Header Fields Too Large",
            .legal_reasons => "Unavailable For Legal Reasons",

            .server_error => "Internal Server Error",
            .not_implemented => "Not Implemented",
            .bad_gateway => "Bad Gateway",
            .unavailable => "Service Unavailable",
            .gateway_timeout => "Gateway Timeout",
            .version_not_supported => "HTTP Version Not Supported",
            .variant_negotiates => "Variant Also Negotiates",
            .insufficient_storage => "Insufficient Storage",
            .loop_detected => "Loop Detected",
            .not_extended => "Not Extended",
            .network_auth_required => "Network Authentication Required",
        };
    }
};
